from app.core.config import Settings, get_settings
from app.core.exceptions import ProviderConfigurationError
from app.infrastructure.embeddings.base import (
    BGEEmbeddingProvider,
    EmbeddingProvider,
    GeminiEmbeddingProvider,
    HashEmbeddingProvider,
    OpenAIEmbeddingProvider,
    RemoteHTTPEmbeddingProvider,
)
from app.infrastructure.llm.base import (
    ExtractiveLLMProvider,
    GeminiLLMProvider,
    LLMProvider,
    MockLLMProvider,
    OpenAILLMProvider,
    RemoteHTTPLLMProvider,
)
from app.infrastructure.vector_store.base import ChromaVectorStore, InMemoryVectorStore, VectorStore

_memory_vector_store: InMemoryVectorStore | None = None


def build_embedding_provider(settings: Settings | None = None) -> EmbeddingProvider:
    settings = settings or get_settings()
    provider = settings.embedding_provider.lower()

    if provider == "bge":
        return BGEEmbeddingProvider(settings.embedding_model_name)

    if provider == "hash":
        return HashEmbeddingProvider()

    if provider == "openai":
        return OpenAIEmbeddingProvider(
            api_key=settings.openai_api_key,
            model_name=settings.openai_embedding_model_name,
        )

    if provider == "gemini":
        return GeminiEmbeddingProvider(
            api_key=settings.gemini_api_key,
            model_name=settings.gemini_embedding_model_name,
        )

    if provider == "remote":
        return RemoteHTTPEmbeddingProvider(
            endpoint_url=settings.remote_embedding_url,
            api_key=settings.remote_model_api_key,
            timeout_seconds=settings.remote_request_timeout_seconds,
        )

    raise ProviderConfigurationError(f"Unsupported embedding provider: {settings.embedding_provider}")


def build_vector_store(settings: Settings | None = None) -> VectorStore:
    global _memory_vector_store

    settings = settings or get_settings()
    provider = settings.vector_store_provider.lower()

    if provider == "chroma":
        return ChromaVectorStore(persist_directory=settings.chroma_db_dir)

    if provider == "memory":
        if _memory_vector_store is None:
            _memory_vector_store = InMemoryVectorStore()
        return _memory_vector_store

    raise ProviderConfigurationError(f"Unsupported vector store provider: {settings.vector_store_provider}")


def build_llm_provider(settings: Settings | None = None) -> LLMProvider:
    settings = settings or get_settings()
    provider = settings.llm_provider.lower()

    if provider == "mock":
        return MockLLMProvider(
            "This response is generated by the mock provider. Configure OpenAI or Gemini for real generation."
        )

    if provider == "extractive":
        return ExtractiveLLMProvider()

    if provider == "gemini":
        return GeminiLLMProvider(
            api_key=settings.gemini_api_key,
            model_name=settings.gemini_model_name,
        )

    if provider == "openai":
        return OpenAILLMProvider(
            api_key=settings.openai_api_key,
            model_name=settings.openai_model_name,
        )

    if provider == "remote":
        return RemoteHTTPLLMProvider(
            endpoint_url=settings.remote_llm_url,
            api_key=settings.remote_model_api_key,
            timeout_seconds=settings.remote_request_timeout_seconds,
        )

    raise ProviderConfigurationError(f"Unsupported LLM provider: {settings.llm_provider}")
